language: julia

os:
  - linux

julia:
  - 1.3

notifications:
  email: false

before_install:

script:
  - julia --check-bounds=yes -e 'using Pkg; Pkg.build(); Pkg.test("Multigrid";coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("Multigrid")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
