language: julia

os:
  - osx
  - linux

julia:
  - 0.7
  - 1.0
  - 1.1

notifications:
  email: false

before_install:
#   - julia -e 'Pkg.clone("https://github.com/JuliaInv/jInv.jl","jInv"); Pkg.build("jInv");'
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
  - julia --check-bounds=yes -e 'using Pkg; Pkg.build(); Pkg.test("Multigrid";coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("Multigrid")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
